### ISSUE TITLE
Lägg på design på härbärgets förstasida

### ISSUE THREAD

**Issue by elajth** [noQ-sweden/noQ-Frontend#3]
###Beskrivning

Som en användare av härbärgets förstasida behöver jag ha en grafisk design så att info visas upp tydligt.

###Acceptance Criteria

Förutsatt att jag loggat in
När jag ser förstasidan
Då ser jag tydlig information

###Subtasks

###Definition of Done

OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by Overath** [comment]
Hola @Gafrelek och @Marohaa hur går det här?

**Comment by Gafrelek** [comment]
![image](https://github.com/noQ-sweden/noQ-Frontend/assets/30535027/efdf7800-1d35-4230-a5db-7cf2f8c1e670)
made side menu taking whole height, edited navbar to not take whole height, added react-icon, changed main.jsx behaviour to eliminate scrolling on page

**Comment by Gafrelek** [comment]
![image](https://github.com/noQ-sweden/noQ-Frontend/assets/30535027/2b93439e-55f4-4f8a-a3c7-00812435a2b3)
![image](https://github.com/noQ-sweden/noQ-Frontend/assets/30535027/9da6cf85-c08a-43c7-8096-4d6c97c5fc7f)
added option to hide and expand menu

**Comment by Gafrelek** [comment]
expected view: https://private-user-images.githubusercontent.com/144100961/325156249-256fed01-b5df-4fb4-97e2-0eea8abd33e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODE5NjEsIm5iZiI6MTcxNTY4MTY2MSwicGF0aCI6Ii8xNDQxMDA5NjEvMzI1MTU2MjQ5LTI1NmZlZDAxLWI1ZGYtNGZiNC05N2UyLTBlZWE4YWJkMzNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmUxNTg2ZTYzZTcxYTU4ODM5OTVhOTQyZmU1MTFiN2ViN2Q2ZjExZGE3NGNhZjc3ZTEyMWYxZWZkNzhjNDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tFPYbzxSi9bZ9qhYra2snTdMdO4fPrKDYviUOudTHEY current ![image](https://github.com/noQ-sweden/noQ-Frontend/assets/30535027/2d621960-2f04-4d9e-adf7-8c74f31d30d4)

**Comment by Gafrelek** [comment]
https://github.com/noQ-sweden/noQ-Frontend/assets/30535027/6956e530-c3d3-4764-97a2-a395516cf32b

**Comment by Overath** [comment]
Feedback in #demochannel in Slack
