### ISSUE TITLE
Skapa SEO för NoQ

### ISSUE THREAD

**Issue by MarioDanilo0111** [noQ-sweden/noQ-Frontend#48]
###Beskrivning
Som användare vill jag se tydlig information i webbläsarens flik om vilken sida jag befinner mig på. 
Dessutom vill jag att meta-taggar ska implementeras för att optimera sidans synlighet i sökmotorer, vilket förbättrar sökbarheten och SEO (Search Engine Optimization).

###Acceptance Criteria
Unik titel för varje sida:
Varje sida under pages/ ska ha en unik <title> som korrekt beskriver innehållet på den aktuella sidan och visas korrekt i webbläsarens flik.
Meta-beskrivning på varje sida:
Varje sida ska ha en unik <meta name="description"> som tydligt beskriver innehållet.
Meta-tagg för författare:
Om relevant, ska <meta name="author"> inkluderas.
Meta-tagg för nyckelord:
Varje sida ska ha en <meta name="keywords">-tagg som listar relevanta nyckelord relaterade till sidans innehåll (minst tre nyckelord).

###Subtasks
Uppdatera SEO-komponenten
Implementera react-helmet för att dynamiskt hantera <title> och meta-taggar för varje sida.
Säkerställ att titeln i browserfliken uppdateras baserat på användarens aktuella sida.
Implementera korrekt meta-beskrivning.
Lägg till meta-taggar som description, author, och keywords på varje relevant sida för att optimera för sökmotorer.
Skriv unika och beskrivande meta-taggar för varje enskild sida för att förbättra SEO.
Använd webbläsarens utvecklarverktyg för att kontrollera att alla meta-taggar visas korrekt i <head>-sektionen.

Uppdatera 
Alla filer under pages/ ska uppdateras med korrekta <title>, <meta name="description">, <meta name="keywords"> och <meta name="author"> där det är relevant för sidans innehåll och SEO. Säkerställ att dessa meta-taggar är unika för varje sida för att förbättra användarupplevelsen och sökmotoroptimeringen.

###Definition of Done
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
För demon, beroende på vem som är inloggad behöver detta synas i fliken: Ex om du är inloggad som Tommy Gäst så ska det stå i fliken: noQ - Tommy Gäst
![image](https://github.com/user-attachments/assets/bdf1d13d-3868-414a-b62e-04a946dea3fc)
